sudo: false

language: node_js

node_js:
- 8

script:
- npm run lint
- npm run mocha
- npm run build

notifications:
  email: false

aliases:
  deploy: &deploy
    provider: heroku
    api_key:
      secure: $HEROKU_API_KEY

jobs:
  include:
    - stage: Deploy (development)
      if: tag IS blank
      deploy:
        <<: *deploy
        app: shri-4-nodejs-stage
        on:
          all_branches: true

    - stage: Deploy (production)
      if: tag IS present
      deploy:
        <<: *deploy
        app: shri-4-nodejs
        on:
          tags: true
          all_branches: true
